spring.datasource.url=jdbc:postgresql://localhost:5432/to_do_list
spring.datasource.username=neo
spring.datasource.password=dyalpsoge

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.example.to_do_list.service=DEBUG

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml